version: "3.7"
services:
 postgresqldb:
  image: postgres:14-alpine
  restart: unless-stopped
  environment:
   - POSTGRES_PASSWORD=admin
   - POSTGRES_USER=postgres
   - POSTGRES_DB=mms
  ports: 
  - 5432:5432
  volumes: 
  - db:/var/lib/postgresql
 app:
   depends_on:
    - postgresqldb
   #build: .
   image: souravargade/mortgagemgmsys:v1
   restart: on-failure
   ports:
    - 8080:8080
   environment:
     SPRING_APPLICATION_JSON: '{
       "spring.datasource.url" : "jdbc:postgresql://postgresqldb:5432/mms?allowPublicKeyRetrieval=true&useSSL=false",
       "spring.datasource.username" : "postgres",
       "spring.datasource.password" : "admin",
       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
       "spring.jpa.hibernate.ddl-auto": "update"
       }'
volumes:
 db: